bonnes_adresses_slugfeeder:
    path:  /slugfeeder
    defaults: { _controller: BonnesAdressesBundle:Default:slugfeeder }

bonnes_adresses_detail_ajax:
    path:  /address
    defaults: { _controller: BonnesAdressesBundle:Default:address }
    methods:   [POST]

bonnes_adresses_homepage:
    path:  /{slug}
    defaults: { _controller: BonnesAdressesBundle:Default:index, slug: '' }
    options:
        expose: true
