bonnes_adresses_homepage:
    path:  /
    defaults: { _controller: BonnesAdressesBundle:Default:index }

bonnes_adresses_namepage:
    path:  /address
    defaults: { _controller: BonnesAdressesBundle:Default:address }
    methods:   [POST]

bonnes_adresses_namepage:
    path:  /address/{name}
    defaults: { _controller: BonnesAdressesBundle:Default:details, name }
    methods:   [GET]
