parameters:
#    bonnes_adresses.example.class: Bonnes\AdressesBundle\Example

services:
#    bonnes_adresses.example:
#        class: %bonnes_adresses.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
