parameters:
#    bonnes_adresses.example.class: Bonnes\AdressesBundle\Example

services:
    geojsonmaker:
        class: Bonnes\AdressesBundle\Services\GeojsonMaker
        arguments: [@serializer]

    adresses.admin:
        class: Bonnes\AdressesBundle\Admin\AdresseAdmin
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Adresses", label: "Adresses" }
        arguments: [null, Bonnes\AdressesBundle\Document\Adresse, null]

    my.sitemap.listener:
        class: Bonnes\AdressesBundle\EventListener\SitemapListener
        arguments: [@router, @doctrine_mongodb]
        tags: [{name: "presta.sitemap.listener"}]

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
