parameters:
#    bonnes_adresses.example.class: Bonnes\AdressesBundle\Example

services:
    adresses.admin:
        class: Bonnes\AdressesBundle\Admin\AdresseAdmin
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Adresses", label: "Adresses" }
        arguments: [null, Bonnes\AdressesBundle\Document\Adresse, null]